---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-webapp
  template:
    metadata:
      labels:
        name: go-webapp
    spec:
      containers:
      - name: application
        image: timon02/go-webapp
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000